#cloud-config
write_files:
  - path: /etc/systemd/system/docker.service
    content: |
      [Unit]
      BindsTo=containerd.service
      After=network-online.target firewalld.service containerd.service
      Wants=network-online.target
      Requires=docker.socket
      
      [Service]
      Type=notify
      ExecStart=/usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock --storage-driver=overlay2
      ExecReload=/bin/kill -s HUP $MAINPID
      TimeoutSec=0
      RestartSec=2
      Restart=always
      LimitNOFILE=infinity
      LimitNPROC=infinity
      LimitCORE=infinity
      TasksMax=infinity
      Delegate=yes
      KillMode=process
      
      [Install]
      WantedBy=multi-user.target
runcmd:
  - [systemctl, daemon-reload]
  - [systemctl, restart, docker.service]
